package com.foodvexa.app

import android.content.Intent
import android.graphics.Color
import android.net.Uri
import android.os.Bundle
import android.text.Editable
import android.text.TextWatcher
import android.view.Gravity
import android.widget.*
import androidx.appcompat.app.*
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import org.json.JSONArray
import org.json.JSONObject

data class Product(val name:String,val price:Int,val category:String,val eta:String="20–30 min")

class MainActivity: AppCompatActivity(){
 private val products=listOf(
  Product("Veg Burger",80,"Fast Food"),Product("Masala Dosa",90,"Fast Food"),Product("Chole Bhature",80,"Meals"),
  Product("Veg Sandwich",70,"Fast Food"),Product("Samosa",20,"Snacks"),Product("Kachori",30,"Snacks"),
  Product("Mirchi Bada",30,"Snacks"),Product("Chole Kulche",60,"Meals"),Product("Maggi",50,"Fast Food"),
  Product("Dhokla",60,"Snacks"),Product("Idli",60,"Meals"),Product("Vada Pav",50,"Fast Food"),
  Product("Cake",350,"Birthday"),Product("Cupcake",30,"Birthday"),Product("Cold Drink",40,"Drinks"))
 private val cart=linkedMapOf<String,Int>(); private lateinit var root:FrameLayout; private lateinit var content:LinearLayout; private lateinit var nav:LinearLayout
 private var category="All"; private var query=""; private val prefs by lazy{getSharedPreferences("foodvexa",0)}
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);root=findViewById(R.id.root);ViewCompat.setOnApplyWindowInsetsListener(root){v,i->val x=i.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(0,x.top,0,x.bottom);i};loadCart();home()}
 private fun frame(){root.removeAllViews();val f=FrameLayout(this);val s=ScrollView(this);content=LinearLayout(this);content.orientation=LinearLayout.VERTICAL;content.setPadding(dp(16),dp(12),dp(16),dp(84));s.addView(content);f.addView(s);nav=LinearLayout(this);nav.orientation=LinearLayout.HORIZONTAL;nav.gravity=Gravity.CENTER;nav.setBackgroundColor(Color.WHITE);f.addView(nav,FrameLayout.LayoutParams(-1,dp(64),Gravity.BOTTOM));root.addView(f)}
 private fun home(){frame();val h=LinearLayout(this);h.gravity=Gravity.CENTER_VERTICAL;val logo=ImageView(this);logo.setImageResource(R.drawable.foodvexa_logo);logo.scaleType=ImageView.ScaleType.CENTER_CROP;h.addView(logo,LinearLayout.LayoutParams(dp(64),dp(64)).apply{rightMargin=dp(10)});val tb=LinearLayout(this);tb.orientation=LinearLayout.VERTICAL;tb.addView(t("FOODVEXA",27,true));tb.addView(t("Fresh food • Fast delivery",13,false));h.addView(tb,LinearLayout.LayoutParams(0,-2,1f));h.addView(btn("Profile"){profile()});content.addView(h);content.addView(btn("⌖  Select delivery location"){location()},lp(0,10,0,8));val search=EditText(this);search.hint="Search food, sweets, fast food...";search.singleLine=true;search.setText(query);content.addView(search,lp(0,4,0,10));search.addTextChangedListener(object:TextWatcher{override fun afterTextChanged(e:Editable?){query=e.toString();render()};override fun beforeTextChanged(s:CharSequence?,a:Int,c:Int,d:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){}});val bs=LinearLayout(this);bs.orientation=LinearLayout.HORIZONTAL;listOf("20% OFF\nFresh & Fast","HOT DEALS\nOrder Today","FOODVEXA\nYour Food, Your Way").forEach{v->val x=t(v,17,true);x.gravity=Gravity.CENTER;x.setTextColor(Color.WHITE);x.background=round("#FF5A36",18);bs.addView(x,LinearLayout.LayoutParams(dp(245),dp(105)).apply{setMargins(0,0,dp(8),0)})};content.addView(HorizontalScrollView(this).apply{isHorizontalScrollBarEnabled=false;addView(bs)});content.addView(t("Categories",21,true),lp(0,18,0,7));val cs=LinearLayout(this);listOf("All","Fast Food","Snacks","Meals","Birthday","Drinks").forEach{c->cs.addView(btn(c){category=c;home()})};content.addView(HorizontalScrollView(this).apply{isHorizontalScrollBarEnabled=false;addView(cs)});content.addView(t(if(category=="All")"Popular near you" else category,21,true),lp(0,18,0,7));render();content.addView(btn("Cart (${count()}) • ₹${total()}"){cartScreen()},lp(0,12,0,0));bottom()}
 private fun render(){val title=if(category=="All")"Popular near you" else category;var at=-1;for(i in 0 until content.childCount)if((content.getChildAt(i) as? TextView)?.text==title){at=i;break};if(at<0)return;while(content.childCount>at+1)content.removeViewAt(at+1);products.filter{(category=="All"||it.category==category)&&(query.isBlank()||it.name.contains(query,true)||it.category.contains(query,true))}.forEach{p->val c=LinearLayout(this);c.orientation=LinearLayout.VERTICAL;c.setPadding(dp(14),dp(10),dp(14),dp(10));c.background=round("#F4F4F4",18);c.setOnClickListener{detail(p)};c.addView(t(p.name,18,true));c.addView(t("Fresh & Hot • ${p.eta}",13,false));val r=LinearLayout(this);r.gravity=Gravity.CENTER_VERTICAL;r.addView(t("₹${p.price}",17,true),LinearLayout.LayoutParams(0,-2,1f));r.addView(btn("+ Add"){add(p)});c.addView(r);content.addView(c,lp(0,7,0,0))}}
 private fun bottom(){nav.removeAllViews();listOf("Home","Search","Orders","Cart","Profile").forEach{x->nav.addView(btn(x){when(x){"Home","Search"->home();"Orders"->orders();"Cart"->cartScreen();else->profile()}}),LinearLayout.LayoutParams(0,64,1f))}}
 private fun cartScreen(){frame();content.addView(t("Your Cart",27,true));if(cart.isEmpty()){content.addView(t("Your cart is empty",17,false),lp(0,25,0,10));content.addView(btn("Browse Food"){home()})}else{cart.keys.toList().forEach{n->val p=products.first{it.name==n};val r=LinearLayout(this);r.gravity=Gravity.CENTER_VERTICAL;r.addView(t("$n\n₹${p.price} each",16,true),LinearLayout.LayoutParams(0,-2,1f));r.addView(btn("−"){change(p,-1);cartScreen()});r.addView(t("${cart[n]}",16,true),lp(8,0,8,0));r.addView(btn("+"){change(p,1);cartScreen()});content.addView(r,lp(0,8,0,0))};content.addView(t("Subtotal: ₹${total()}",20,true),lp(0,20,0,3));content.addView(btn("Proceed to Checkout"){checkout()},lp(0,10,0,0));content.addView(btn("Clear Cart"){cart.clear();save();cartScreen()},lp(0,5,0,0))};bottom()}
 private fun orders(){frame();content.addView(t("Order History",27,true));val a=JSONArray(prefs.getString("orders","[]")!!);if(a.length()==0)content.addView(t("No orders yet.",17,false),lp(0,25,0,0));for(i in a.length()-1 downTo 0){val o=a.getJSONObject(i);val c=LinearLayout(this);c.orientation=LinearLayout.VERTICAL;c.setPadding(dp(14),dp(10),dp(14),dp(10));c.background=round("#F4F4F4",18);c.addView(t("Order #${o.optString("id")}",17,true));c.addView(t("${o.optString("items")} • ₹${o.optInt("total")}",14,false));c.addView(t("${o.optString("status")} • ${o.optString("payment")}",13,false));content.addView(c,lp(0,8,0,0))};bottom()}
 private fun profile(){frame();content.addView(t("Profile",27,true));content.addView(t("Foodvexa customer account",14,false),lp(0,3,0,12));listOf("My Orders","Address Book","Payment Settings","Notifications","Call Support","Navigate to Shop","Feedback","Appearance","About Foodvexa","Logout").forEach{x->content.addView(btn(x){when(x){"My Orders"->orders();"Address Book"->location();"Payment Settings"->info("Payment Settings","COD is available. UPI needs a real merchant integration before it can be enabled.");"Notifications"->info("Notifications","No new notifications.");"Call Support"->info("Support","Support number is not configured yet. No fake number is used.");"Navigate to Shop"->navigate();"Feedback"->feedback();"Appearance"->appearance();"About Foodvexa"->info("About","Professional food ordering foundation. Real backend, admin, payments and live tracking can be connected without fake success states.");else->info("Logout","No account session is configured yet.")}}},lp(0,4,0,0))};bottom()}
 private fun detail(p:Product){val b=LinearLayout(this);b.orientation=LinearLayout.VERTICAL;b.addView(t(p.name,23,true));b.addView(t("₹${p.price} • ${p.eta} • Fresh & Hot",15,false),lp(0,7,0,5));b.addView(btn("Add to Cart"){add(p)});b.addView(btn("Buy Now"){add(p);checkout()});AlertDialog.Builder(this).setTitle("Food details").setView(b).setNegativeButton("Close",null).show()}
 private fun checkout(){if(cart.isEmpty())return;val b=LinearLayout(this);b.orientation=LinearLayout.VERTICAL;val n=EditText(this);n.hint="Full name (required)";val m=EditText(this);m.hint="10-digit mobile (required)";m.inputType=2;val a=EditText(this);a.hint="Delivery address (required)";b.addView(n);b.addView(m);b.addView(a);val g=RadioGroup(this);val cod=RadioButton(this);cod.text="Cash on Delivery";cod.isChecked=true;val upi=RadioButton(this);upi.text="UPI / Online payment";g.addView(cod);g.addView(upi);b.addView(g);AlertDialog.Builder(this).setTitle("Checkout").setView(b).setPositiveButton("Place Order"){_,_->if(n.text.isBlank()||m.text.length!=10||a.text.isBlank()){toast("Name, 10-digit mobile and address are required.")}else if(upi.isChecked){toast("UPI is not configured yet; no false payment success is shown.")}else{place(n.text.toString(),m.text.toString(),a.text.toString())}}.setNegativeButton("Cancel",null).show()}
 private fun place(n:String,m:String,a:String){val ar=JSONArray(prefs.getString("orders","[]")!!);ar.put(JSONObject().apply{put("id",System.currentTimeMillis().toString().takeLast(6));put("items",cart.entries.joinToString{it.key+" x"+it.value});put("total",total());put("status","Order placed • COD");put("payment","Cash on Delivery");put("customer",n);put("mobile",m);put("address",a)});prefs.edit().putString("orders",ar.toString()).apply();cart.clear();save();info("Order placed","COD order saved locally. Real admin/live status can be connected next.")}
 private fun location(){val e=EditText(this);e.hint="Enter delivery location";e.setText(prefs.getString("location",""));AlertDialog.Builder(this).setTitle("Delivery location").setView(e).setPositiveButton("Save"){_,_->prefs.edit().putString("location",e.text.toString()).apply();home()}.setNegativeButton("Cancel",null).show()}
 private fun feedback(){val e=EditText(this);e.hint="Write feedback";AlertDialog.Builder(this).setTitle("Feedback").setView(e).setPositiveButton("Submit"){_,_->toast("Feedback saved on this device.")}.setNegativeButton("Cancel",null).show()}
 private fun appearance(){val a=arrayOf("Use device theme","Light theme","Dark theme");AlertDialog.Builder(this).setTitle("Appearance").setSingleChoiceItems(a,prefs.getInt("theme",0)){d,w->prefs.edit().putInt("theme",w).apply();AppCompatDelegate.setDefaultNightMode(when(w){1->AppCompatDelegate.MODE_NIGHT_NO;2->AppCompatDelegate.MODE_NIGHT_YES;else->AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM});d.dismiss()}.show()}
 private fun navigate(){try{startActivity(Intent(Intent.ACTION_VIEW,Uri.parse("geo:0,0?q=Foodvexa")))}catch(_:Exception){toast("Map app not available.")}}
 private fun add(p:Product){cart[p.name]=(cart[p.name]?:0)+1;save();toast("${p.name} added")};private fun change(p:Product,d:Int){val n=(cart[p.name]?:0)+d;if(n<=0)cart.remove(p.name)else cart[p.name]=n;save()};private fun count()=cart.values.sum();private fun total()=cart.entries.sumOf{products.first{p->p.name==it.key}.price*it.value};private fun save(){val o=JSONObject();cart.forEach{(k,v)->o.put(k,v)};prefs.edit().putString("cart",o.toString()).apply()};private fun loadCart(){val o=JSONObject(prefs.getString("cart","{}")!!);o.keys().forEach{cart[it]=o.optInt(it)}}
 private fun info(a:String,b:String)=AlertDialog.Builder(this).setTitle(a).setMessage(b).setPositiveButton("OK",null).show();private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show();private fun t(s:String,z:Float,b:Boolean)=TextView(this).apply{text=s;textSize=z;if(b)setTypeface(null,android.graphics.Typeface.BOLD)};private fun btn(s:String,f:()->Unit)=Button(this).apply{text=s;setOnClickListener{f()}};private fun round(h:String,r:Int)=android.graphics.drawable.GradientDrawable().apply{setColor(Color.parseColor(h));cornerRadius=dp(r).toFloat()};private fun dp(x:Int)=(x*resources.displayMetrics.density).toInt();private fun lp(l:Int,t:Int,r:Int,b:Int)=LinearLayout.LayoutParams(-1,-2).apply{setMargins(dp(l),dp(t),dp(r),dp(b))}
}
