package com.foodvexa.app

import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.net.Uri
import android.os.Bundle
import android.text.InputType
import android.view.Gravity
import android.widget.*
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import androidx.appcompat.app.AppCompatDelegate
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import org.json.JSONArray
import org.json.JSONObject

data class Product(val name:String,val price:Int,val category:String,val eta:String="20–30 min")

class MainActivity:AppCompatActivity(){
 companion object{const val SHOP_LOCATION="Khation ki Dhani, Ward No. 16, Ganeshpura, Nawalgarh"}
 private val products=listOf(Product("Veg Burger",80,"Fast Food"),Product("Masala Dosa",90,"Fast Food"),Product("Chole Bhature",80,"Meals"),Product("Veg Sandwich",70,"Fast Food"),Product("Samosa",20,"Snacks"),Product("Kachori",30,"Snacks"),Product("Mirchi Bada",30,"Snacks"),Product("Chole Kulche",60,"Meals"),Product("Maggi",50,"Fast Food"),Product("Dhokla",60,"Snacks"),Product("Idli",60,"Meals"),Product("Vada Pav",50,"Fast Food"),Product("Cake",350,"Birthday"),Product("Cupcake",30,"Birthday"),Product("Cold Drink",40,"Drinks"))
 private val cart=linkedMapOf<String,Int>();private lateinit var root:FrameLayout;private lateinit var content:LinearLayout;private val prefs by lazy{getSharedPreferences("foodvexa",MODE_PRIVATE)};private var selectedCategory="All";private var query=""
 private val orange=Color.rgb(255,90,54);private val green=Color.rgb(7,59,50);private val ink=Color.rgb(35,35,42);private val muted=Color.rgb(105,105,115);private val cardColor=Color.rgb(250,250,252)
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);root=findViewById(R.id.root);ViewCompat.setOnApplyWindowInsetsListener(root){v,i->val bars=i.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(0,bars.top,0,bars.bottom);i};loadCart();showHome()}
 private fun setupBase(){root.removeAllViews();val frame=FrameLayout(this);val scroll=ScrollView(this);content=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(16),dp(12),dp(16),dp(82))};scroll.addView(content);frame.addView(scroll,FrameLayout.LayoutParams(-1,-1));val nav=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER;setPadding(dp(6),dp(4),dp(6),dp(4));setBackgroundColor(Color.WHITE);elevation=dp(8).toFloat()};listOf("⌂","⌕","▣","🛒","♙").forEachIndexed{index,icon->val b=TextView(this).apply{text=icon;textSize=22f;gravity=Gravity.CENTER;setTextColor(ink);typeface=Typeface.DEFAULT_BOLD;background=rounded(Color.WHITE,12);setOnClickListener{when(index){0,1->showHome();2->showOrders();3->showCart();4->showProfile()}}};nav.addView(b,LinearLayout.LayoutParams(0,dp(52),1f).apply{leftMargin=dp(2);rightMargin=dp(2)})};frame.addView(nav,FrameLayout.LayoutParams(-1,dp(62),Gravity.BOTTOM));root.addView(frame)}
 private fun showHome(){setupBase();val header=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL};val logo=ImageView(this).apply{setImageResource(R.drawable.foodvexa_logo);scaleType=ImageView.ScaleType.CENTER_CROP;contentDescription="Foodvexa logo"};header.addView(logo,LinearLayout.LayoutParams(dp(58),dp(58)).apply{rightMargin=dp(10)});val brand=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};brand.addView(label("FOODVEXA",26f,true,green));brand.addView(label("Fresh food • Fast delivery",13f,false,muted));header.addView(brand,LinearLayout.LayoutParams(0,-2,1f));val profile=TextView(this).apply{text="♙";textSize=30f;gravity=Gravity.CENTER;setTextColor(green);setOnClickListener{showProfile()}};header.addView(profile,LinearLayout.LayoutParams(dp(52),dp(52)));content.addView(header)
 val loc=prefs.getString("location","").orEmpty();content.addView(primaryButton(if(loc.isBlank())"⌖  Select delivery location" else "⌖  $loc"){locationDialog()},margin(0,12,0,10))
 val search=EditText(this).apply{hint="Search food, sweets, fast food...";setHintTextColor(muted);setTextColor(ink);setSingleLine(true);inputType=InputType.TYPE_CLASS_TEXT;setPadding(dp(14),dp(2),dp(14),dp(2));background=rounded(Color.WHITE,14)};content.addView(search,margin(0,0,0,12));search.setText(query);search.addTextChangedListener(object:android.text.TextWatcher{override fun afterTextChanged(s:android.text.Editable?){query=s?.toString().orEmpty();renderProducts()};override fun beforeTextChanged(s:CharSequence?,st:Int,c:Int,a:Int){};override fun onTextChanged(s:CharSequence?,st:Int,b:Int,c:Int){}})
 val bannerScroll=HorizontalScrollView(this).apply{isHorizontalScrollBarEnabled=false;overScrollMode=HorizontalScrollView.OVER_SCROLL_NEVER};val bannerRow=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};bannerRow.addView(heroBanner("HOT & FRESH FOOD","UP TO 20% OFF","Order now • Fast delivery"));bannerRow.addView(heroBanner("FRESH MEALS, FAST","DELICIOUS EVERY DAY","Quality food at your doorstep"));bannerRow.addView(heroBanner("FOODVEXA SPECIAL","LIMITED OFFERS","Fresh • Hot • Fast"));bannerScroll.addView(bannerRow);content.addView(bannerScroll,margin(0,0,0,4))
 content.addView(label("Categories",22f,true,ink),margin(0,20,0,8));val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};listOf("All","Fast Food","Snacks","Meals","Birthday","Drinks").forEach{c->val x=if(c==selectedCategory)primaryButton(c){selectedCategory=c;showHome()}else actionButton(c){selectedCategory=c;showHome()};row.addView(x,LinearLayout.LayoutParams(-2,dp(44)).apply{rightMargin=dp(7)})};content.addView(HorizontalScrollView(this).apply{isHorizontalScrollBarEnabled=false;addView(row)});content.addView(label(if(selectedCategory=="All")"Popular near you" else selectedCategory,22f,true,ink),margin(0,20,0,8));renderProducts();content.addView(primaryButton("Cart (${cartCount()}) • ₹${cartTotal()}"){showCart()},margin(0,14,0,0))}
 private fun heroBanner(title:String,offer:String,sub:String):LinearLayout{val card=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(18),dp(14),dp(12),dp(14));background=rounded(Color.rgb(22,28,28),22)};val left=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val small=label("FOODVEXA",12f,true,Color.WHITE);left.addView(small);left.addView(label(title,20f,true,Color.WHITE),margin(0,3,0,2));left.addView(label(sub,12f,false,Color.rgb(220,225,220)));val cta=primaryButton("ORDER NOW  ›"){};left.addView(cta,margin(0,9,0,0));card.addView(left,LinearLayout.LayoutParams(0,-1,1f));val right=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setPadding(dp(8),0,0,0)};val img=ImageView(this).apply{setImageResource(R.drawable.foodvexa_logo);scaleType=ImageView.ScaleType.CENTER_INSIDE};right.addView(img,LinearLayout.LayoutParams(dp(88),dp(62)));val badge=label(offer,15f,true,Color.WHITE).apply{gravity=Gravity.CENTER;background=rounded(orange,18);setPadding(dp(10),dp(8),dp(10),dp(8))};right.addView(badge);card.addView(right,LinearLayout.LayoutParams(dp(120),-1));return card.apply{layoutParams=LinearLayout.LayoutParams(dp(330),dp(174)).apply{rightMargin=dp(10)}}}
 private fun renderProducts(){val title=if(selectedCategory=="All")"Popular near you" else selectedCategory;var ti=-1;for(i in 0 until content.childCount)if(content.getChildAt(i) is TextView&&(content.getChildAt(i)as TextView).text.toString()==title){ti=i;break};if(ti<0)return;while(content.childCount>ti+1)content.removeViewAt(ti+1);products.filter{(selectedCategory=="All"||it.category==selectedCategory)&&(query.isBlank()||it.name.contains(query,true)||it.category.contains(query,true))}.forEach{p->val card=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(15),dp(13),dp(12),dp(13));background=rounded(cardColor,18);setOnClickListener{productDetails(p)}};val top=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};top.addView(label(p.name,18f,true,ink),LinearLayout.LayoutParams(0,-2,1f));top.addView(primaryButton("+ ADD"){addToCart(p);toast("${p.name} added to cart")});card.addView(top);card.addView(label("Fresh & Hot • ${p.eta}",13f,false,muted),margin(0,5,0,4));card.addView(label("₹${p.price}",18f,true,green));content.addView(card,margin(0,7,0,0))}}
 private fun showCart(){setupBase();content.addView(label("Your Cart",27f,true,green));if(cart.isEmpty()){content.addView(label("Your cart is empty",17f,false,muted),margin(0,25,0,10));content.addView(primaryButton("Browse Food"){showHome()});return};cart.keys.toList().forEach{name->val p=products.first{it.name==name};val row=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};row.addView(label("$name\n₹${p.price} each",16f,true,ink),LinearLayout.LayoutParams(0,-2,1f));row.addView(actionButton("−"){changeCart(p,-1);showCart()});row.addView(label("${cart[name]?:0}",16f,true,ink),margin(8,0,8,0));row.addView(actionButton("+"){changeCart(p,1);showCart()});content.addView(row,margin(0,8,0,0))};content.addView(label("Subtotal: ₹${cartTotal()}",21f,true,green),margin(0,20,0,3));content.addView(primaryButton("Proceed to Checkout"){checkoutDialog()},margin(0,10,0,0));content.addView(actionButton("Clear Cart"){cart.clear();saveCart();showCart()},margin(0,6,0,0))}
 private fun showOrders(){setupBase();content.addView(label("Order History",27f,true,green));val orders=JSONArray(prefs.getString("orders","[]")?:"[]");if(orders.length()==0)content.addView(label("No orders yet.",17f,false,muted),margin(0,25,0,0));for(i in orders.length()-1 downTo 0){val o=orders.getJSONObject(i);val card=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(14),dp(12),dp(14),dp(12));background=rounded(cardColor,16)};card.addView(label("Order #${o.optString("id")}",17f,true,ink));card.addView(label("${o.optString("items")} • ₹${o.optInt("total")}",14f,false,muted));card.addView(label("${o.optString("status")} • ${o.optString("payment")}",13f,false,green));content.addView(card,margin(0,8,0,0))}}
 private fun showProfile(){setupBase();content.addView(label("Profile",27f,true,green));content.addView(label("Foodvexa customer account",14f,false,muted),margin(0,3,0,12));listOf("My Orders","Address Book","Payment Settings","Notifications","Call Support","Navigate to Shop","Feedback","Appearance","About Foodvexa","Logout").forEach{a->content.addView(actionButton(a){when(a){"My Orders"->showOrders();"Address Book"->locationDialog();"Payment Settings"->info("Payment Settings","COD is available. UPI needs a real merchant integration before it can be enabled.");"Notifications"->info("Notifications","No new notifications.");"Call Support"->info("Support","Support number is not configured yet. No fake number is used.");"Navigate to Shop"->navigateToShop();"Feedback"->feedbackDialog();"Appearance"->appearanceDialog();"About Foodvexa"->info("About Foodvexa","Professional food ordering app.");"Logout"->info("Logout","No account session is configured yet.")}},margin(0,4,0,0))}}
 private fun productDetails(p:Product){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};box.addView(label(p.name,23f,true,green));box.addView(label("₹${p.price} • ${p.eta} • Fresh & Hot",15f,false,muted),margin(0,7,0,8));box.addView(primaryButton("Add to Cart"){addToCart(p);toast("Added to cart")});box.addView(actionButton("Buy Now"){addToCart(p);checkoutDialog()});AlertDialog.Builder(this).setTitle("Food details").setView(box).setNegativeButton("Close",null).show()}
 private fun checkoutDialog(){if(cart.isEmpty())return;val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};val name=EditText(this).apply{hint="Full name (required)"};val mobile=EditText(this).apply{hint="10-digit mobile (required)";inputType=InputType.TYPE_CLASS_PHONE};val address=EditText(this).apply{hint="Delivery address (required)"};box.addView(name);box.addView(mobile);box.addView(address);val group=RadioGroup(this);val cod=RadioButton(this).apply{text="Cash on Delivery";isChecked=true};val upi=RadioButton(this).apply{text="UPI / Online payment"};group.addView(cod);group.addView(upi);box.addView(group);AlertDialog.Builder(this).setTitle("Checkout").setView(box).setPositiveButton("Place Order"){_,_->val phone=mobile.text.toString().trim();if(name.text.toString().trim().isEmpty()||phone.length!=10||address.text.toString().trim().isEmpty())toast("Name, 10-digit mobile and address are required.")else if(upi.isChecked)toast("UPI is not configured yet; no false payment success is shown.")else placeOrder(name.text.toString().trim(),phone,address.text.toString().trim())}.setNegativeButton("Cancel",null).show()}
 private fun placeOrder(name:String,mobile:String,address:String){val orders=JSONArray(prefs.getString("orders","[]")?:"[]");val items=cart.entries.joinToString{"${it.key} x${it.value}"};orders.put(JSONObject().apply{put("id",System.currentTimeMillis().toString().takeLast(6));put("items",items);put("total",cartTotal());put("status","Order placed • COD");put("payment","Cash on Delivery");put("customer",name);put("mobile",mobile);put("address",address)});prefs.edit().putString("orders",orders.toString()).apply();cart.clear();saveCart();info("Order placed","COD order saved locally. Real admin/live status can be connected next.")}
 private fun locationDialog(){val input=EditText(this).apply{hint="Enter delivery location";setText(prefs.getString("location","")?:"")};AlertDialog.Builder(this).setTitle("Delivery location").setView(input).setPositiveButton("Save"){_,_->val v=input.text.toString().trim();prefs.edit().putString("location",v).apply();showHome()}.setNegativeButton("Cancel",null).show()}
 private fun feedbackDialog(){val input=EditText(this).apply{hint="Write feedback"};AlertDialog.Builder(this).setTitle("Feedback").setView(input).setPositiveButton("Submit"){_,_->toast("Feedback saved on this device.")}.setNegativeButton("Cancel",null).show()}
 private fun appearanceDialog(){val choices=arrayOf("Use device theme","Light theme","Dark theme");val current=prefs.getInt("theme",0);AlertDialog.Builder(this).setTitle("Appearance").setSingleChoiceItems(choices,current){d,w->prefs.edit().putInt("theme",w).apply();AppCompatDelegate.setDefaultNightMode(when(w){1->AppCompatDelegate.MODE_NIGHT_NO;2->AppCompatDelegate.MODE_NIGHT_YES;else->AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM});d.dismiss()}.show()}
 private fun navigateToShop(){try{startActivity(Intent(Intent.ACTION_VIEW,Uri.parse("geo:0,0?q=${Uri.encode(SHOP_LOCATION)}")))}catch(_:Exception){toast("Map app not available.")}}
 private fun info(t:String,m:String)=AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("OK",null).show()
 private fun addToCart(p:Product){cart[p.name]=(cart[p.name]?:0)+1;saveCart()};private fun changeCart(p:Product,d:Int){val n=(cart[p.name]?:0)+d;if(n<=0)cart.remove(p.name)else cart[p.name]=n;saveCart()};private fun cartCount()=cart.values.sum();private fun cartTotal()=cart.entries.sumOf{e->products.first{it.name==e.key}.price*e.value};private fun saveCart(){val o=JSONObject();cart.forEach{(k,v)->o.put(k,v)};prefs.edit().putString("cart",o.toString()).apply()};private fun loadCart(){val o=JSONObject(prefs.getString("cart","{}")?:"{}");o.keys().forEach{cart[it]=o.optInt(it)}}
 private fun label(s:String,z:Float,b:Boolean,c:Int)=TextView(this).apply{text=s;textSize=z;setTextColor(c);if(b)typeface=Typeface.DEFAULT_BOLD};private fun primaryButton(s:String,f:()->Unit)=actionButton(s,f).apply{setTextColor(Color.WHITE);background=rounded(orange,14)};private fun actionButton(s:String,f:()->Unit)=Button(this).apply{text=s;textSize=13f;setOnClickListener{f()}};private fun rounded(c:Int,r:Int)=android.graphics.drawable.GradientDrawable().apply{setColor(c);cornerRadius=dp(r).toFloat()};private fun dp(v:Int)=(v*resources.displayMetrics.density).toInt();private fun margin(l:Int,t:Int,r:Int,b:Int)=LinearLayout.LayoutParams(-1,-2).apply{setMargins(dp(l),dp(t),dp(r),dp(b))};private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()
}